vscode:
  extensions:
    - equinusocio.vsc-material-theme-icons@1.2.0:JY/GxjbjHN78dpQfT47roQ==
    - octref.vetur@0.30.0:H8aqTikA9GiRqj3r+E9ryA==
    - hollowtree.vue-snippets@0.1.12:R8kIKADMUL4rp+KMfYtsHg==